### ISSUE TITLE
Path for development

### ISSUE THREAD

**Issue by simonwinter** [sunnysideup/silverstripe-webpack_requirements_backend#1]
When I'm running this module inside an environment where we are using a port as part of the URL (e.g. inside a local docker container - you'd possibly use something like http://localhost:8081), the URL of the CSS file becomes distorted.

Instead of getting:

`protocol://domain:webpack-port/file-path`

you'd get:

`protocol://localhost:8081:webpack-port/file-path`

It'd be really handy if there was a config option to specify the domain where webpack is running rather than just relying on the absolute path.

https://github.com/sunnysideup/silverstripe-webpack_requirements_backend/blob/ac6bb0f829be1852d69c4f77f0852c9e891882d1/code/control/WebpackPageControllerExtension.php#L55

**Comment by sunnysideup** [comment]
fixed now ... please test and then I will tag version.
